# Advent of Code 2024

## Day 10

### Part One - Calculate the sum of the scores of all trailheads on the topographic map

In [1]:
import numpy as np

In [2]:
def search_trail(trailhead, num, data):
    max_rows, max_cols = data.shape
    x, y = trailhead
    endpoints = []

    # return the endpoint if the trail reached the end
    if num == 9:
        return [(x, y)]  

    # check for possible steps 
    for dx, dy in [(-1, 0), (1, 0), (0, -1), (0, 1)]:  # up, down, left, right
        nx, ny = x + dx, y + dy
        if 0 <= nx < max_rows and 0 <= ny < max_cols:  # ensure within bounds
            if data[nx, ny] - num == 1:  # ensure the difference in potential step is exactly 1
                # recursive call to collect all endpoints
                endpoints += search_trail((nx, ny), num + 1, data)
    
    return endpoints

In [3]:
import numpy as np

# get task data
data = []
with open("10-input.txt", "r") as file:
    for line in file:
        data.append([int(num) for num in line.strip()])
data = np.array(data)
print(data)

# initialize dictionary for keeping "(trailhead, endpoint): count" pairs 
trails_found = {}

for r, row in enumerate(data):
    for c, col in enumerate(row):
        if data[r][c] == 0:  # start from trailheads
            trailhead = (r, c)
            # get all endpoints for the current trailhead
            endpoints = search_trail(trailhead, 0, data)
            for endpoint in endpoints:
                # count the occurrences of (trailhead, endpoint) pairs
                if (trailhead, endpoint) not in trails_found:
                    trails_found[(trailhead, endpoint)] = 1
                else:
                    trails_found[(trailhead, endpoint)] += 1

print(f"There are {len(trails_found)} unique paths")

[[7 6 5 ... 5 4 5]
 [8 3 4 ... 4 3 2]
 [9 2 0 ... 2 0 1]
 ...
 [6 9 0 ... 3 0 3]
 [5 4 3 ... 2 1 2]
 [4 3 4 ... 1 0 1]]
There are 652 unique paths


### Part Two - Calculate the sum of the ratings of all trailheads

In [4]:
# ratings are values in trails_found dictionary from the above, so all we need to do is sum it
sum(trails_found.values())

1432